### PR TITLE
Refactor sample app

### PR DESCRIPTION
**Pull request by alibagherifam**
This PR refactors sample app provides the following benefits:

- Improve code readability by renaming and re-ordering current functions and extracting new ones.
- Rename classes to better distinguish between the Fragment and Activity samples.
- Fix the typo in the sample app's [theme](https://github.com/cafebazaar/BazaarPay/blob/main/app/src/main/res/values/themes.xml).
- Align code with new documentation on #19.
- Use material components instead of built-in ones to take advantage of the material theme already implemented for the project.
- Extract string literals into resources and add Persian locale to the sample app.
- Change the package name of the sample app to preserve its common part with the SDK itself.

### CODE REVIEW

**Comment by hamidrezasahraei** [comment]
@alibagherifam 
This PR looks good to me but recently we have removed English support from the SDK and this caused some conflicts with this PR, Would you please resolve them?

**Comment by alibagherifam** [comment]
@hamidrezasahraei 
Thank you for reviewing my pull request. I was aware of #23 and waiting for it to be merged into the `dev` branch so I can resolve the merge conflict and make the necessary changes. The pull request is now ready for your review.

**Comment by AlirezaSoltaniJazi** [comment]
Bug ID: 1
Priority: Low
Title: Main page - The elements margin removed
Actual Result:
We had a margin for elements on the main page, but now we no longer have it.
Expected Result:
Add 5-10 px margin to the elements. 
Attachment:
image

**Comment by alibagherifam** [comment]
Thank you for reviewing my pull request and catching that mistake. The margin attribute was declared for all UI elements separately. I tried to replace them with a single margin attribute at the root element but forgot that it has no parent to set the margin from. So now, I replaced that with a padding attribute, and everything should be fine.

Also, I improved the overall appearance of both screens by:
1. Adding AppBar component with screen names on it.
2. Changing some colors for better Dark Mode.
3. Adding guidelines for more manageable margins in the future.
4. Styling some UI components.

**Comment by AlirezaSoltaniJazi** [comment]
Thanks for your participation @alibagherifam

**Review by AlirezaSoltaniJazi — APPROVED** [review]
LGTM 
@hamidrezasahraei

**Pull request merged**
