### PR TITLE
Fix commit api problem and upgrade gradle verison

### PR DESCRIPTION
**Pull request by Rezasahebi76**
Handle `KotlinNullPointerException` of commit api by changing its return type to `Response<Unit>`.
When we receive 204 as response code, `KotlinNullPointerException` is throws due to empty response body. This is handled by replacing `ResponseBody` with `Response<Unit>`.

### CODE REVIEW

**Comment by hamid97m** [comment]
Thank you for your contribution. Due to the current risks associated with AGP updates, we kindly request that you remove the changes related to updating AGP. We are actively working on resolving this issue. Regarding the problem you encountered, it appears that consuming the response body on another thread and using `Response<Unit>` could potentially fix it. We were unable to reproduce this problem, as it is working fine on our SampleApp. To address the issue, we have released a new hotfix for you to test and verify if the problem has been resolved.

**Comment by Rezasahebi76** [comment]
I would appreciate it if you mention where exactly I can find the hotfix version to test it

**Comment by hamid97m** [comment]
> I would appreciate it if you mention where exactly I can find the hotfix version to test it

It's 5.0.3

**Comment by Rezasahebi76** [comment]
Thank you. The issue has been resolved. I will close this pull request.

**Pull request closed without merging**
